### PR TITLE
Introduced support to AlmaLinux and RockyLinux on kernel-crawler

### PR DESCRIPTION
**Pull request by dark-vex**

### CODE REVIEW

**Comment by lilx1ao** [comment]
looks good. if you have this tested then I will give ma thumbs-up

**Comment by dark-vex** [comment]
@lilx1ao I did a similar PR to OSS Falco kernel-crawler and is working fine, since this one works slightly different, I will re-test it

**Comment by dark-vex** [comment]
@lilx1ao I have tested it and found an issue, now I have fixed it and is working

AlmaLinux
```
 ➜ docker run sysdig-probe-builder:latest -C AlmaLinux 5.14.0-70.26.1.el9_0
Checking repositories
Listing packages
=== 5.14.0-70.26.1.el9_0.x86_64 ===
 http://repo.almalinux.org/almalinux/9.0/BaseOS/x86_64/os/Packages/kernel-modules-5.14.0-70.26.1.el9_0.x86_64.rpm
 http://repo.almalinux.org/almalinux/9.0/BaseOS/x86_64/os/Packages/kernel-5.14.0-70.26.1.el9_0.x86_64.rpm
 http://repo.almalinux.org/almalinux/9/BaseOS/x86_64/os/Packages/kernel-5.14.0-70.26.1.el9_0.x86_64.rpm
 http://repo.almalinux.org/almalinux/9.0/BaseOS/x86_64/os/Packages/kernel-core-5.14.0-70.26.1.el9_0.x86_64.rpm
 http://repo.almalinux.org/almalinux/9.0/AppStream/x86_64/os/Packages/kernel-devel-5.14.0-70.26.1.el9_0.x86_64.rpm
 http://repo.almalinux.org/almalinux/9/BaseOS/x86_64/os/Packages/kernel-modules-5.14.0-70.26.1.el9_0.x86_64.rpm
 http://repo.almalinux.org/almalinux/9/BaseOS/x86_64/os/Packages/kernel-core-5.14.0-70.26.1.el9_0.x86_64.rpm
 http://repo.almalinux.org/almalinux/9/AppStream/x86_64/os/Packages/kernel-devel-5.14.0-70.26.1.el9_0.x86_64.rpm
```

RockyLinux
```
 ➜ docker run sysdig-probe-builder:latest -C RockyLinux 5.14.0-70.26.1.el9_0
Checking repositories
Listing packages
=== 5.14.0-70.26.1.el9_0.x86_64 ===
 http://dl.rockylinux.org/pub/rocky/9/BaseOS/x86_64/os/Packages/k/kernel-core-5.14.0-70.26.1.el9_0.x86_64.rpm
 http://dl.rockylinux.org/pub/rocky/9/BaseOS/x86_64/os/Packages/k/kernel-5.14.0-70.26.1.el9_0.x86_64.rpm
 http://dl.rockylinux.org/pub/rocky/9.0/BaseOS/x86_64/os/Packages/k/kernel-5.14.0-70.26.1.el9_0.x86_64.rpm
 http://dl.rockylinux.org/pub/rocky/9.0/BaseOS/x86_64/os/Packages/k/kernel-modules-5.14.0-70.26.1.el9_0.x86_64.rpm
 http://dl.rockylinux.org/pub/rocky/9.0/BaseOS/x86_64/os/Packages/k/kernel-core-5.14.0-70.26.1.el9_0.x86_64.rpm
 http://dl.rockylinux.org/pub/rocky/9/BaseOS/x86_64/os/Packages/k/kernel-modules-5.14.0-70.26.1.el9_0.x86_64.rpm
 http://dl.rockylinux.org/pub/rocky/9/AppStream/x86_64/os/Packages/k/kernel-devel-5.14.0-70.26.1.el9_0.x86_64.rpm
 http://dl.rockylinux.org/pub/rocky/9.0/AppStream/x86_64/os/Packages/k/kernel-devel-5.14.0-70.26.1.el9_0.x86_64.rpm
```

**Comment by lilx1ao** [comment]
great! and version 8 is also working?

**Comment by dark-vex** [comment]
Yep, it works also with version 8:

- AlmaLinux
```
 ➜ docker run sysdig-probe-builder:latest -C AlmaLinux 4.18.0-372.13.1.el8_6
Checking repositories
Listing packages
=== 4.18.0-372.13.1.el8_6.x86_64 ===
 http://repo.almalinux.org/almalinux/8/BaseOS/x86_64/os/Packages/kernel-devel-4.18.0-372.13.1.el8_6.x86_64.rpm
 http://repo.almalinux.org/almalinux/8/BaseOS/x86_64/os/Packages/kernel-core-4.18.0-372.13.1.el8_6.x86_64.rpm
 http://repo.almalinux.org/almalinux/8/BaseOS/x86_64/os/Packages/kernel-4.18.0-372.13.1.el8_6.x86_64.rpm
 http://repo.almalinux.org/almalinux/8.6/BaseOS/x86_64/os/Packages/kernel-core-4.18.0-372.13.1.el8_6.x86_64.rpm
 http://repo.almalinux.org/almalinux/8.6/BaseOS/x86_64/os/Packages/kernel-4.18.0-372.13.1.el8_6.x86_64.rpm
 http://repo.almalinux.org/almalinux/8.6/BaseOS/x86_64/os/Packages/kernel-modules-4.18.0-372.13.1.el8_6.x86_64.rpm
 http://repo.almalinux.org/almalinux/8.6/BaseOS/x86_64/os/Packages/kernel-devel-4.18.0-372.13.1.el8_6.x86_64.rpm
 http://repo.almalinux.org/almalinux/8/BaseOS/x86_64/os/Packages/kernel-modules-4.18.0-372.13.1.el8_6.x86_64.rpm
```

- RockyLinux
```
 ➜ docker run sysdig-probe-builder:latest -C RockyLinux 4.18.0-372.13.1.el8_6
Checking repositories
Listing packages
=== 4.18.0-372.13.1.el8_6.x86_64 ===
 http://dl.rockylinux.org/pub/rocky/8/BaseOS/x86_64/os/Packages/k/kernel-devel-4.18.0-372.13.1.el8_6.x86_64.rpm
 http://dl.rockylinux.org/pub/rocky/8.6/BaseOS/x86_64/os/Packages/k/kernel-4.18.0-372.13.1.el8_6.x86_64.rpm
 http://dl.rockylinux.org/pub/rocky/8/BaseOS/x86_64/os/Packages/k/kernel-4.18.0-372.13.1.el8_6.x86_64.rpm
 http://dl.rockylinux.org/pub/rocky/8.6/BaseOS/x86_64/os/Packages/k/kernel-devel-4.18.0-372.13.1.el8_6.x86_64.rpm
 http://dl.rockylinux.org/pub/rocky/8.6/BaseOS/x86_64/os/Packages/k/kernel-modules-4.18.0-372.13.1.el8_6.x86_64.rpm
 http://dl.rockylinux.org/pub/rocky/8.6/BaseOS/x86_64/os/Packages/k/kernel-core-4.18.0-372.13.1.el8_6.x86_64.rpm
 http://dl.rockylinux.org/pub/rocky/8/BaseOS/x86_64/os/Packages/k/kernel-core-4.18.0-372.13.1.el8_6.x86_64.rpm
 http://dl.rockylinux.org/pub/rocky/8/BaseOS/x86_64/os/Packages/k/kernel-modules-4.18.0-372.13.1.el8_6.x86_64.rpm
```

**Review by lilx1ao — APPROVED** [review]
good with me!

**Comment by iurly** [comment]
@dark-vex fine with me, too!

**Review by iurly — APPROVED** [review]

**Comment by dark-vex** [comment]
Thanks for your review as well @iurly ! Feel free to merge it since I don't have the permission to-do that on this repo :)

**Pull request merged**
